### ISSUE TITLE
Can I use casbin-authz running dockerd with unix socket?

### ISSUE THREAD

**Issue by odg0318** [casbin/casbin-authz-plugin#10]
Hello.

In the document, tcp connection is used in systemd configuration
```
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 --authorization-plugin=casbin-authz-plugin
```
I don't want to use tcp connection but unix socket set by default.

Can I use casbin-authz running dockerd with unix socket?

**Comment by hsluoyz** [comment]
It's mainly the communication mechanism of Docker daemon. Casbin-authz is just a middleware of Docker. As far as I know, Docker daemon supports UNIX domain socket, see here: https://docs.docker.com/engine/reference/commandline/dockerd

**Comment by odg0318** [comment]
@hsluoyz I know docker supports unix socket.
But there is no `casbin` configuration about unix socket.
As I said, below lines are written in documentation.
```
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 --authorization-plugin=casbin-authz-plugin
```

One more question, `/usr/bin/docker` is right?

**Comment by hsluoyz** [comment]
Can you try to modify that line to:
```
ExecStart=/usr/bin/docker daemon -H unix:///var/run/docker.sock --authorization-plugin=casbin-authz-plugin
```
and make sure your Docker daemon is listening to that UNIX socket.

Are you referring to Docker renames its daemon to ``dockerd``? I don't know how Docker evolves these days as I developed based on an old version. Can you help update the commands if it has changed and make a PR? Thanks.

**Comment by odg0318** [comment]
@hsluoyz Ok, I'll make a PR for it.
