### ISSUE TITLE
isolation for users within the containers

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#13]
Hi
I am PhD student and I am going to create docker authorization plugin model to provide isolation for users within the docker container by using access control.

therefore, Could you help me please to create this model ?

Best,
Ibrahim

**Comment by hsluoyz** [comment]
How do you want to provide the isolation? How to create the model is based on your access control objective. You can see if these models (https://github.com/casbin/casbin#supported-models) can help you.

**Comment by hsluoyz** [comment]
Closed as stale.
