### ISSUE TITLE
run authorization plugin

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#14]
Hi,

what are the differences between runs the authorization plugin directly on the host or inside a container ?

Many thanks.

Ibrahim

**Comment by hsluoyz** [comment]
No difference, it is a static binary.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by alobaidan** [comment]
Many thanks Hsluoyz

**Comment by alobaidan** [comment]
Can anyone help me how to install Casbin inside container and run it ? I have installed Casbin on the host and run it but I would like to install and run it inside container.

**Comment by hsluoyz** [comment]
This question has nothing to do with Casbin.
