### ISSUE TITLE
Step 8-Changed the policy 

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#15]
Hi
I have Changed the policy in step 8 but I got the same output which is ``Error response from daemon: authorization denied by plugin casbin-authz-plugin: Access denied by casbin plugin``

I changed the policy to:

```csv
p, /v1.29/images/json, GET
```

could you tell me how to solve this problem please ?

Ibrahim

**Comment by hsluoyz** [comment]
What Docker command did you test? The policy ``p, /v1.29/images/json, GET`` only allows to ``GET`` on the Docker operation: ``/v1.29/images/json``. You were probably using a different command, at least the version ``v1.29`` may be different.

As the README said, you should use ``journalctl`` to see the Casbin deny logs, like:

```
obj: /v1.30/whatever, act: GET res: denied
```

Then you know the ``obj`` and ``act`` that being denied. And add this request to policy like:

```
p, /v1.30/whatever, GET
```

Then restart Casbin plugin and it should work.
