### ISSUE TITLE
 alice, data1, read

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#16]
Hi, 

what do you mean in data1 ? is it container , image or object within the image.

Many Thanks,
Ibrahim

**Comment by alobaidan** [comment]
in the basic_policy.csv
i would like to add some policies to this file. this is your example, Alice, data1, read

alice can read data1. what does data1 means ( container,image or object  within the image) ?

many thanks
ibrahim

**Comment by hsluoyz** [comment]
The ``basic_policy.csv`` in this repo (https://github.com/casbin/casbin-authz-plugin/blob/master/examples/basic_policy.csv) is:

```csv
p, /_ping, GET
p, /v1.27/images/json, GET
```

**Comment by hsluoyz** [comment]
``Alice, data1, read`` is the general example for Casbin. You should read the Casbin documents to understand it: https://casbin.org/docs/en/overview

**Comment by alobaidan** [comment]
OK. 
Thank you very much
