### ISSUE TITLE
p, /v1.27/images/json, GET

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#17]
Hi, 

Is it possible to add user to this policy "p, /v1.27/images/json, GET" ?
for example I would like to make this policy enable just for Bob. (p, Bob /v1.27/images/json, GET)

I added subject in the basic_model.conf file but I got error message from the sock when I run the previous policy with user.

Many Thanks
Ibrahim

**Comment by hsluoyz** [comment]
You can see a similar issue here: https://github.com/casbin/casbin-authz-plugin/issues/4#issuecomment-381453726

**Comment by hsluoyz** [comment]
Closed as stale.
