### ISSUE TITLE
Recommended system of using Casbin's basic model?

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#19]
Hi,

could you recommend any available system to run this model with the subject:

```ini
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

because i cannot run this model with the subject on the docker so I would like to run the system on any available system.

Many thanks,
Ibrahim

**Comment by hsluoyz** [comment]
Hi @alobaidan , the model you showed is the basic model of Casbin. Many systems that use Casbin support that or use an extension of it like RBAC, ABAC. You can refer to all practical examples here: https://github.com/casbin/casbin#others

**Comment by alobaidan** [comment]
Many Thanks.

**Comment by hsluoyz** [comment]
Closed as resolved.
