### ISSUE TITLE
docker.socket

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#20]
Hi

I would like t edit docker.socket file and make it for a partcuilar user.
example:

```ini
[Socket] 
ListenStream=/var/run/docker.sock
SocketMode=0660
SoketUser=pi
SocketGroup=docker
```
so SocketUser will be equal pi instead of root because I would like to add the subject in the casbin model.
but I got error message from the socket.

is there anyway to make it in the casbin ?

many thanks

**Comment by hsluoyz** [comment]
Similar to: https://github.com/casbin/casbin-authz-plugin/issues/22
