### ISSUE TITLE
cd /usr/lib/docker

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#21]
Hi,

I got this error when i run ``cd /usr/lib/docker  : Not a directory``.

I have run it when I work in single node. Now I have created cluster (supercomputer 4 nodes) but when I want to run casbin plugin I got this error ``cd /usr/lib/docker  : Not a dirctory``.

can you help me please ?

Best
Ibrahim

**Comment by hsluoyz** [comment]
The https://github.com/casbin/casbin-authz-plugin#run guide just needs a folder to place Casbin policy files. It can be any other folder. Maybe recent Docker versions do not use ``/usr/lib/docker`` folder any more. You can use another folder. Just make sure Casbin plugin can find the files.

**Comment by alobaidan** [comment]
Hi, 
i used /var/lib/docker and created examples but when i wnat to copy the basic_model.conf examples/. igot the following error.
pi@IbrahimController:/var/lib/docker $ sudo cp basic_model.conf examples/.
cp: cannot stat 'basic_model.conf': No such file or directory


Many thansk for helping me

**Comment by alobaidan** [comment]
I have solved it .
Thanks.
