### ISSUE TITLE
Rootlesskit 

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#22]
Hi ,

With Rootlesskit that will provided by docker. Can I add subject to the casbin model ?

**Comment by hsluoyz** [comment]
What user do you want subject to refer to?

**Comment by alobaidan** [comment]
For example 
request_definition]
r = sub, obj, act

**Comment by hsluoyz** [comment]
I mean the Enforce() call.

**Comment by alobaidan** [comment]
i want to make the docker socket idntify the user , for example i have two users (Pi and Bob) i want only Pi can get access the the containers. I want to add the subject to the authorisation plugin

**Comment by hsluoyz** [comment]
You need to find a way to pass the username (Pi or Bob) into Enforce(), which has nothing to do with Casbin. So you shouldn't ask whether Casbin supports it or not. It's up to you.
