### ISSUE TITLE
 sudo docker exec -d b5a94da7aa67 touch xxx  

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#24]
Hi i added this rule to the policy file 

```
p, /v1.38/containers/b5a94da7aa67/exec , POST
```

(b5a94da7aa67) container ID
but when i run the folowing command i got error from authorisation plugin, the authorisation plugin deny the request. 

```
sudo docker exec -d b5a94da7aa67 touch xxx
Error response from daemon: authorization denied by plugin casbin-authz-plugin:                                                                              
Access denied by casbin plugin
```

**Comment by hsluoyz** [comment]
Add some logs to troubleshoot.

**Comment by alobaidan** [comment]
![error5](https://user-images.githubusercontent.com/14161637/65145187-d8044080-da10-11e9-979d-c59c143bc069.png)
 this is the policy file

![er6](https://user-images.githubusercontent.com/14161637/65145202-e0f51200-da10-11e9-95af-d7a03248262e.png)
and this is the error

**Comment by hsluoyz** [comment]
Print the request.

**Comment by alobaidan** [comment]
I would like to create file inside running container

**Comment by alobaidan** [comment]
example ibrahim file. i would like to add this file inide container b5a94da7aa67

**Comment by alobaidan** [comment]
as well as , **head /containers/{id}/archive** this command not work

**Comment by alobaidan** [comment]
sorry for disturb you.

also how i can add docker container ID diff to the policy file becuser is not in the API refrence page

**Comment by hsluoyz** [comment]
I don't get it.

**Comment by alobaidan** [comment]
I have some questions based on casbin:

1- what is the policy should be in the policy file to run container because is not in the api. (ex/ docker run -i -t ubuntu /bin/bash )
2- how to run docker exec (contrainer ID) touch file. (add file to running container) ex (docker exec -d (containerID) touch file)
3- how to run docker exec (contrainer ID) rm file. (rmove file from rununig container) ex ((docker exec -d (containerID) rm file)
4- what is the policy to run container diff command because is not in the api. ex( (docker container ID diff)

thank you

**Comment by alobaidan** [comment]
i solve it. thank you
