### ISSUE TITLE
Apply group policy

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-authz-plugin#4]
> Hello,
>
> In the blog post (https://www.twistlock.com/2016/02/18/docker-authz-plugins-twistlocks-contribution-to-the-docker-community/), there was a sample using RBAC authorization.
>
> The “ContainerOps” group can perform “docker –run” and “docker – rm”
{“name”:”policy_1″,”users”:[“ContainerOps”],”actions”:[“container_run”, “container_rm”]}
The audit team can only perform “docker – list”, but nothing else
{“name”:”policy_2″,”users”:[“AuditGroup”],”actions”:[“container”], “readonly”:true}
Alice can run all Docker commands: {“name”:”policy_3″,”users”:[“alice”],”actions”:[“*”]}
> Is it possible to extend the current project to do so ?
> Thanks :)

Hi @ahmed-bacha, this repo is also a Docker authorization plugin. And it's based on [Casbin](https://github.com/casbin/casbin), a new authorization library which supports flexible access control models like ACL, RBAC, ABAC.

So I think this is what you need if you want a RBAC function. And I think it's better than the twistlock one. I'm glad to improve it further if you are interested in it and have any other requests:)

**Comment by ahmed-bacha** [comment]
Hi @hsluoyz, 

Thanks for the ping, I'll have a look at this plugin and CASBIN and give you a feedback ASAP.

Regards,

**Comment by hsluoyz** [comment]
@caoruidong why Casbin authz plugin (and twistlock plugin) requires to enable TLS is because Casbin needs to extract the subject (aka user name) from the TLS certificate (aka the common name). This extraction is done by Docker daemon. So now there are two options:

1. Use Casbin authz plugin without subject. Just like the built-in Casbin model and policy shown in README. So you don't need to enable TLS. But in this mode, you can only control which operation is allowed (for everyone). You can't choose who can perform the operations.

2. You may want to use another mechanism to provide the subject. For example, you built another authentication mechanism to integrate with Docker. And you want to use the authenticated user name as Casbin's suject. If this is the case, you can tell me how your authentication works and we can discuss how to design the interaction between the authentication and Casbin.

**Comment by hsluoyz** [comment]
It is indeed a good idea to use Linux users as subject. But as far as I know, Docker daemon communicates with Docker client via sockets. So Docker daemon only see network requests sent from sockets and there is actually no such thing like Linux user in a request. I guess you have to think of some other authentication measures that work for sockets.

**Comment by caoruidong** [comment]
@hsluoyz Agreed. Either use TLS mode, or customize moby's code to build docker personally. I'll think about it.
