### ISSUE TITLE
will dockerlint restrict user from installing ssh and telnet ?

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-authz-plugin#6]
Hi @daashayani, this repo is also a Docker authorization plugin. And it's based on [Casbin](https://github.com/casbin/casbin), a new authorization library which supports flexible access control models like ACL, RBAC, ABAC.

If you are saying that if the Docker user can be restricted from installing a software inside a Docker container, I'm afraid not.

**Comment by lyqabc123** [comment]
@hackerchai
