### ISSUE TITLE
Instructions on running and enabling is not working

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [casbin/casbin-authz-plugin#8]
I always get an error when trying to run the plugin

```
Oct 13 14:35:52 azure-staging systemd[1]: Started Docker RBAC & ABAC Authorization Plugin based on Casbin.
-- Subject: Unit casbin-authz-plugin.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit casbin-authz-plugin.service has finished starting up.
-- 
-- The start-up result is done.
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: 2017/10/13 14:35:52 Casbin model: examples/basic_model.conf
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: 2017/10/13 14:35:52 Casbin policy: examples/basic_policy.csv
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: panic: open examples/basic_model.conf: no such file or directory
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: goroutine 1 [running]:
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: panic(0x79a200, 0xc82000f290)
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: github.com/casbin/casbin/model.Model.LoadModel(0xc82000f230, 0x87f1e0, 0x19)
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/local/go/bin/src/github.com/casbin/casbin/model/model.go:95 +0x85
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: github.com/casbin/casbin.(*Enforcer).LoadModel(0xc82004a700)
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/local/go/bin/src/github.com/casbin/casbin/enforcer.go:163 +0x7f
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: github.com/casbin/casbin.(*Enforcer).InitWithFile(0xc82004a700, 0x87f1e0, 0x19, 0x87f200, 0x19)
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/local/go/bin/src/github.com/casbin/casbin/enforcer.go:109 +0xf6
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: github.com/casbin/casbin.NewEnforcer(0xc82003de08, 0x2, 0x2, 0x717220)
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/local/go/bin/src/github.com/casbin/casbin/enforcer.go:73 +0x4b7
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: main.newPlugin(0x87f1e0, 0x19, 0x87f200, 0x19, 0xc82000aff0, 0x0, 0x0)
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/local/go/bin/src/github.com/casbin/casbin-authz-plugin/plugin.go:25 +0x18b
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]: main.main()
Oct 13 14:35:52 azure-staging casbin-authz-plugin[46424]:         /usr/local/go/bin/src/github.com/casbin/casbin-authz-plugin/main.go:32 +0x32a
Oct 13 14:35:52 azure-staging systemd[1]: casbin-authz-plugin.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 13 14:35:52 azure-staging systemd[1]: casbin-authz-plugin.service: Unit entered failed state.
Oct 13 14:35:52 azure-staging systemd[1]: casbin-authz-plugin.service: Failed with result 'exit-code'.
```

Nothing happens when I Enable the authorization plugin

P.S.
- I am not a golang developer so debugging this is very hard for me

**Comment by hsluoyz** [comment]
> panic: open examples/basic_model.conf: no such file or directory

This error means the Casbin model file ``basic_model.conf`` is not found. You need to create a folder named ``examples`` right beside the plugin binary ``casbin-authz-plugin``, and put this file into the folder. Then retry to start it.

**Comment by Dean-Christian-Armada** [comment]
I actually tried doing that in /usr/lib/docker/examples/ but still nothing happened when I attempt the commands below

```
$ systemctl daemon-reload
$ systemctl enable casbin-authz-plugin
$ systemctl start casbin-authz-plugin
```

**Comment by hsluoyz** [comment]
The difficulty of this issue is that it's hard to know the current directory of the plugin, as it is started by docker.  I have updated the code to print out the current directory to console in this commit: https://github.com/casbin/casbin-authz-plugin/commit/20b337e2a0474f0a6ce02afdcb1f55644eaff60a

So you can see what the cd is in your environment, then put the ``examples/basic_model.conf`` into that path.

**Comment by Dean-Christian-Armada** [comment]
Your update shows the **current directory** awesome. It says that I am in the `/` as stated below:

```
Oct 13 16:10:51 azure-staging systemd[1]: Started Docker RBAC & ABAC Authorization Plugin based on Casbin.
-- Subject: Unit casbin-authz-plugin.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit casbin-authz-plugin.service has finished starting up.
-- 
-- The start-up result is done.
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: 2017/10/13 16:10:51 Current directory: /
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: 2017/10/13 16:10:51 Casbin model: examples/basic_model.conf
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: 2017/10/13 16:10:51 Casbin policy: examples/basic_policy.csv
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: panic: open examples/basic_model.conf: no such file or directory
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: goroutine 1 [running]:
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: panic(0x79b2a0, 0xc82000f290)
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: github.com/casbin/casbin/model.Model.LoadModel(0xc82000f230, 0x880480, 0x19)
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/local/go/bin/src/github.com/casbin/casbin/model/model.go:95 +0x85
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: github.com/casbin/casbin.(*Enforcer).LoadModel(0xc82004a700)
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/local/go/bin/src/github.com/casbin/casbin/enforcer.go:163 +0x7f
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: github.com/casbin/casbin.(*Enforcer).InitWithFile(0xc82004a700, 0x880480, 0x19, 0x8804a0, 0x19)
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/local/go/bin/src/github.com/casbin/casbin/enforcer.go:109 +0xf6
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: github.com/casbin/casbin.NewEnforcer(0xc82003ddc8, 0x2, 0x2, 0x718240)
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/local/go/bin/src/github.com/casbin/casbin/enforcer.go:73 +0x4b7
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: main.newPlugin(0x880480, 0x19, 0x8804a0, 0x19, 0xc82000b010, 0x0, 0x0)
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/local/go/bin/src/github.com/casbin/casbin-authz-plugin/plugin.go:25 +0x18b
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]: main.main()
Oct 13 16:10:51 azure-staging casbin-authz-plugin[15467]:         /usr/local/go/bin/src/github.com/casbin/casbin-authz-plugin/main.go:36 +0x4a8
Oct 13 16:10:51 azure-staging systemd[1]: casbin-authz-plugin.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 13 16:10:51 azure-staging systemd[1]: casbin-authz-plugin.service: Unit entered failed state.
Oct 13 16:10:51 azure-staging systemd[1]: casbin-authz-plugin.service: Failed with result 'exit-code'.
```

Why is the current directory there? I'm not in that location when I'm running the `systemctl` commands nor when I was showing the logs.

Also, I would like to know more on the **memory string to load model and use database to load policy rules**. It will be very helpful if that option is on the README as well

**Comment by hsluoyz** [comment]
> Why is the current directory there? I'm not in that location when I'm running the systemctl commands nor when I was showing the logs.

My wrong. The plugin is a standalone systemd service instead of started by docker. So we cannot blame Docker:) Based on [this post](https://unix.stackexchange.com/questions/200654/executing-chdir-before-starting-systemd-service), the default current directory for a systemd service is ``/``. You can change it by adding a line in ``[Service]`` section like:
```
[Service]
WorkingDirectory=/usr/local
```
to the service configuration file: ``systemd/casbin-authz-plugin.service``

> Also, I would like to know more on the memory string to load model and use database to load policy rules. It will be very helpful if that option is on the README as well

This plugin is actually just a wrapper for the real Casbin library. And most of the useful docs is inside Casbin documentation: https://github.com/casbin/casbin#documentation. Casbin supports different ways to persist model and policy rules. See these links: https://github.com/casbin/casbin/wiki/Model-persistence and https://github.com/casbin/casbin/wiki/Policy-persistence

**Comment by Dean-Christian-Armada** [comment]
By the way I have tried your solution above and you need to change the WorkingDirectory from `/usr/local` to `/usr/local/go/bin/src/github.com/casbin/casbin-authz-plugin`

Then for the systemctl edit for docker, you need to run `systemctl status docker` to the docker systemd service location as in my case is `/etc/systemd/system/docker.service`

But you can just use `systemctl edit docker` to edit the ExecStart then put like

```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 --authorization-plugin=casbin-authz-plugin
```

to override the command as all stated in https://success.docker.com/KBase/Using_systemd_to_control_the_Docker_daemon

Personally, it's better to **Run the plugin as a systemd service**


Also, on the **Stop and uninstall the plugin as a systemd service** section please change the **img-authz-plugin** to **casbin-authz-plugin**


Please also include in the README to do `systemctl restart casbin-authz-plugin` if they made changes on the policy to reflect the changes

P.S.
I already made it work thanks for the assistance; I really appreciate it! :)

**Comment by hsluoyz** [comment]
Good to hear you solved it! Feel free to improve the README.md about your experience:)

**Comment by Dean-Christian-Armada** [comment]
@hsluoyz , I'll do a fork anytime soon :)
